[
  {
    "signature": "create(java.lang.Throwable t)",
    "name": "create",
    "containingClass": {
      "qualifiedName": "com.google.common.util.concurrent.FutureFallback",
      "name": "FutureFallback",
      "isArray": false
    },
    "targetClass": "com.google.common.util.concurrent.FutureFallback",
    "isVarArgs": false,
    "returnType": {
      "qualifiedName": "com.google.common.util.concurrent.ListenableFuture",
      "name": "ListenableFuture",
      "isArray": false
    },
    "parameters": [
      {
        "type": {
          "qualifiedName": "java.lang.Throwable",
          "name": "Throwable",
          "isArray": false
        },
        "name": "t"
      }
    ],
    "paramTags": [
      {
        "parameter": {
          "type": {
            "qualifiedName": "java.lang.Throwable",
            "name": "Throwable",
            "isArray": false
          },
          "name": "t"
        },
        "comment": "the exception that made the future fail. If the future's get method throws an ExecutionException, then the cause is passed to this method. Any other thrown object is passed unaltered.",
        "kind": "PARAM",
        "condition": ""
      }
    ],
    "throwsTags": []
  }
]